// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#pragma once

#include "dataBlock.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class DataBlock final {
public:
    using CppType = ::DataBlock;
    using JniType = jobject;

    using Boxed = DataBlock;

    ~DataBlock();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    DataBlock();
    friend ::djinni::JniClass<DataBlock>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/wta/weather/DataBlock") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/util/ArrayList;)V") };
    const jfieldID field_summary { ::djinni::jniGetFieldID(clazz.get(), "summary", "Ljava/lang/String;") };
    const jfieldID field_icon { ::djinni::jniGetFieldID(clazz.get(), "icon", "Ljava/lang/String;") };
    const jfieldID field_data { ::djinni::jniGetFieldID(clazz.get(), "data", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
