// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#pragma once

#include "djinni_support.hpp"
#include "weatherController.hpp"

namespace djinni_generated {

class WeatherController final : ::djinni::JniInterface<::WeatherController, WeatherController> {
public:
    using CppType = std::shared_ptr<::WeatherController>;
    using JniType = jobject;

    using Boxed = WeatherController;

    ~WeatherController();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<WeatherController>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<WeatherController>::get()._toJava(jniEnv, c)}; }

private:
    WeatherController();
    friend ::djinni::JniClass<WeatherController>;
    friend ::djinni::JniInterface<::WeatherController, WeatherController>;

};

}  // namespace djinni_generated
