// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#pragma once

#include <cstdint>
#include <string>
#include <utility>

struct Alert final {
    std::string title;
    int64_t expires;
    std::string alert_description;
    std::string uri;

    Alert(std::string title,
          int64_t expires,
          std::string alert_description,
          std::string uri)
    : title(std::move(title))
    , expires(std::move(expires))
    , alert_description(std::move(alert_description))
    , uri(std::move(uri))
    {}
};
