// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#pragma once

#include "dataPoint.hpp"
#include <string>
#include <utility>
#include <vector>

struct DataBlock final {
    std::string summary;
    std::string icon;
    std::vector<DataPoint> data;

    DataBlock(std::string summary,
              std::string icon,
              std::vector<DataPoint> data)
    : summary(std::move(summary))
    , icon(std::move(icon))
    , data(std::move(data))
    {}
};
