// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#pragma once

#include "alert.hpp"
#include "dataBlock.hpp"
#include "dataPoint.hpp"
#include "flags.hpp"
#include <cstdint>
#include <string>
#include <utility>
#include <vector>

struct Forecast final {
    double latitude;
    double longitude;
    std::string timezone;
    int32_t offset;
    DataPoint currently;
    DataBlock minutely;
    DataBlock hourly;
    DataBlock daily;
    std::vector<Alert> alerts;
    Flags flags;

    Forecast(double latitude,
             double longitude,
             std::string timezone,
             int32_t offset,
             DataPoint currently,
             DataBlock minutely,
             DataBlock hourly,
             DataBlock daily,
             std::vector<Alert> alerts,
             Flags flags)
    : latitude(std::move(latitude))
    , longitude(std::move(longitude))
    , timezone(std::move(timezone))
    , offset(std::move(offset))
    , currently(std::move(currently))
    , minutely(std::move(minutely))
    , hourly(std::move(hourly))
    , daily(std::move(daily))
    , alerts(std::move(alerts))
    , flags(std::move(flags))
    {}
};
