// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#pragma once

#include <cstdint>
#include <string>
#include <vector>

class NetworkController {
public:
    virtual ~NetworkController() {}

    virtual std::vector<uint8_t> get(const std::string & URI) = 0;

    virtual std::vector<uint8_t> post(const std::string & URI, const std::vector<uint8_t> & body) = 0;
};
