// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#pragma once

#include "forecast.hpp"
#include <memory>

class NetworkController;

class WeatherController {
public:
    virtual ~WeatherController() {}

    virtual Forecast forecast(double latitude, double longitude) = 0;

    static std::shared_ptr<WeatherController> create_with_network_controller(const std::shared_ptr<NetworkController> & controller);
};
