// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#pragma once

#include <cstdint>
#include <memory>
#include <vector>

class NetworkController;

class WeatherController {
public:
    virtual ~WeatherController() {}

    virtual void forecast(double latitude, double longitude) = 0;

    static std::shared_ptr<WeatherController> create_with_network_controller(const std::shared_ptr<NetworkController> & controller);

    virtual void receiveData(const std::vector<uint8_t> & data) = 0;
};
