// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

package com.wta.weather;

public final class Alert {


    /*package*/ final String title;

    /*package*/ final long expires;

    /*package*/ final String alertDescription;

    /*package*/ final String uri;

    public Alert(
            String title,
            long expires,
            String alertDescription,
            String uri) {
        this.title = title;
        this.expires = expires;
        this.alertDescription = alertDescription;
        this.uri = uri;
    }

    public String getTitle() {
        return title;
    }

    public long getExpires() {
        return expires;
    }

    public String getAlertDescription() {
        return alertDescription;
    }

    public String getUri() {
        return uri;
    }
}
