// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

package com.wta.weather;

public final class DataPoint {


    /*package*/ final long time;

    /*package*/ final String summary;

    /*package*/ final String icon;

    /*package*/ final Long sunriseTime;

    /*package*/ final Long sunsetTime;

    /*package*/ final Double moonPhase;

    /*package*/ final Double nearestStormDistance;

    /*package*/ final Double nearestStormBearing;

    /*package*/ final double precipIntensity;

    /*package*/ final Double precipIntensityMax;

    /*package*/ final Long precipIntensityMaxTime;

    /*package*/ final double precipProbability;

    /*package*/ final String precipType;

    /*package*/ final Double precipAccumulation;

    /*package*/ final Double temperature;

    /*package*/ final Double temperatureMin;

    /*package*/ final Long temperatureMinTime;

    /*package*/ final Double temperatureMax;

    /*package*/ final Long temperatureMaxTime;

    /*package*/ final Double apparentTemperature;

    /*package*/ final Double apparentTemperatureMax;

    /*package*/ final Long apparentTemperatureMaxTime;

    /*package*/ final Double apparentTemperatureMin;

    /*package*/ final Long apparentTemperatureMinTime;

    /*package*/ final double dewPoint;

    /*package*/ final double windSpeed;

    /*package*/ final double windBearing;

    /*package*/ final double cloudCover;

    /*package*/ final double humidity;

    /*package*/ final double pressure;

    /*package*/ final double visibility;

    /*package*/ final double ozone;

    public DataPoint(
            long time,
            String summary,
            String icon,
            Long sunriseTime,
            Long sunsetTime,
            Double moonPhase,
            Double nearestStormDistance,
            Double nearestStormBearing,
            double precipIntensity,
            Double precipIntensityMax,
            Long precipIntensityMaxTime,
            double precipProbability,
            String precipType,
            Double precipAccumulation,
            Double temperature,
            Double temperatureMin,
            Long temperatureMinTime,
            Double temperatureMax,
            Long temperatureMaxTime,
            Double apparentTemperature,
            Double apparentTemperatureMax,
            Long apparentTemperatureMaxTime,
            Double apparentTemperatureMin,
            Long apparentTemperatureMinTime,
            double dewPoint,
            double windSpeed,
            double windBearing,
            double cloudCover,
            double humidity,
            double pressure,
            double visibility,
            double ozone) {
        this.time = time;
        this.summary = summary;
        this.icon = icon;
        this.sunriseTime = sunriseTime;
        this.sunsetTime = sunsetTime;
        this.moonPhase = moonPhase;
        this.nearestStormDistance = nearestStormDistance;
        this.nearestStormBearing = nearestStormBearing;
        this.precipIntensity = precipIntensity;
        this.precipIntensityMax = precipIntensityMax;
        this.precipIntensityMaxTime = precipIntensityMaxTime;
        this.precipProbability = precipProbability;
        this.precipType = precipType;
        this.precipAccumulation = precipAccumulation;
        this.temperature = temperature;
        this.temperatureMin = temperatureMin;
        this.temperatureMinTime = temperatureMinTime;
        this.temperatureMax = temperatureMax;
        this.temperatureMaxTime = temperatureMaxTime;
        this.apparentTemperature = apparentTemperature;
        this.apparentTemperatureMax = apparentTemperatureMax;
        this.apparentTemperatureMaxTime = apparentTemperatureMaxTime;
        this.apparentTemperatureMin = apparentTemperatureMin;
        this.apparentTemperatureMinTime = apparentTemperatureMinTime;
        this.dewPoint = dewPoint;
        this.windSpeed = windSpeed;
        this.windBearing = windBearing;
        this.cloudCover = cloudCover;
        this.humidity = humidity;
        this.pressure = pressure;
        this.visibility = visibility;
        this.ozone = ozone;
    }

    public long getTime() {
        return time;
    }

    public String getSummary() {
        return summary;
    }

    public String getIcon() {
        return icon;
    }

    public Long getSunriseTime() {
        return sunriseTime;
    }

    public Long getSunsetTime() {
        return sunsetTime;
    }

    public Double getMoonPhase() {
        return moonPhase;
    }

    public Double getNearestStormDistance() {
        return nearestStormDistance;
    }

    public Double getNearestStormBearing() {
        return nearestStormBearing;
    }

    public double getPrecipIntensity() {
        return precipIntensity;
    }

    public Double getPrecipIntensityMax() {
        return precipIntensityMax;
    }

    public Long getPrecipIntensityMaxTime() {
        return precipIntensityMaxTime;
    }

    public double getPrecipProbability() {
        return precipProbability;
    }

    public String getPrecipType() {
        return precipType;
    }

    public Double getPrecipAccumulation() {
        return precipAccumulation;
    }

    public Double getTemperature() {
        return temperature;
    }

    public Double getTemperatureMin() {
        return temperatureMin;
    }

    public Long getTemperatureMinTime() {
        return temperatureMinTime;
    }

    public Double getTemperatureMax() {
        return temperatureMax;
    }

    public Long getTemperatureMaxTime() {
        return temperatureMaxTime;
    }

    public Double getApparentTemperature() {
        return apparentTemperature;
    }

    public Double getApparentTemperatureMax() {
        return apparentTemperatureMax;
    }

    public Long getApparentTemperatureMaxTime() {
        return apparentTemperatureMaxTime;
    }

    public Double getApparentTemperatureMin() {
        return apparentTemperatureMin;
    }

    public Long getApparentTemperatureMinTime() {
        return apparentTemperatureMinTime;
    }

    public double getDewPoint() {
        return dewPoint;
    }

    public double getWindSpeed() {
        return windSpeed;
    }

    public double getWindBearing() {
        return windBearing;
    }

    public double getCloudCover() {
        return cloudCover;
    }

    public double getHumidity() {
        return humidity;
    }

    public double getPressure() {
        return pressure;
    }

    public double getVisibility() {
        return visibility;
    }

    public double getOzone() {
        return ozone;
    }
}
