// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

package com.wta.weather;

import java.util.ArrayList;

public final class Flags {


    /*package*/ final String darkskyUnavailable;

    /*package*/ final ArrayList<String> darkskyStations;

    /*package*/ final ArrayList<String> datapointStations;

    /*package*/ final ArrayList<String> isdStations;

    /*package*/ final ArrayList<String> lampStations;

    /*package*/ final ArrayList<String> metarStations;

    /*package*/ final String metnoLicense;

    /*package*/ final ArrayList<String> sources;

    /*package*/ final String units;

    public Flags(
            String darkskyUnavailable,
            ArrayList<String> darkskyStations,
            ArrayList<String> datapointStations,
            ArrayList<String> isdStations,
            ArrayList<String> lampStations,
            ArrayList<String> metarStations,
            String metnoLicense,
            ArrayList<String> sources,
            String units) {
        this.darkskyUnavailable = darkskyUnavailable;
        this.darkskyStations = darkskyStations;
        this.datapointStations = datapointStations;
        this.isdStations = isdStations;
        this.lampStations = lampStations;
        this.metarStations = metarStations;
        this.metnoLicense = metnoLicense;
        this.sources = sources;
        this.units = units;
    }

    public String getDarkskyUnavailable() {
        return darkskyUnavailable;
    }

    public ArrayList<String> getDarkskyStations() {
        return darkskyStations;
    }

    public ArrayList<String> getDatapointStations() {
        return datapointStations;
    }

    public ArrayList<String> getIsdStations() {
        return isdStations;
    }

    public ArrayList<String> getLampStations() {
        return lampStations;
    }

    public ArrayList<String> getMetarStations() {
        return metarStations;
    }

    public String getMetnoLicense() {
        return metnoLicense;
    }

    public ArrayList<String> getSources() {
        return sources;
    }

    public String getUnits() {
        return units;
    }
}
