// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

package com.wta.weather;

import java.util.ArrayList;

public final class Forecast {


    /*package*/ final double latitude;

    /*package*/ final double longitude;

    /*package*/ final String timezone;

    /*package*/ final int offset;

    /*package*/ final DataPoint currently;

    /*package*/ final DataBlock minutely;

    /*package*/ final DataBlock hourly;

    /*package*/ final DataBlock daily;

    /*package*/ final ArrayList<Alert> alerts;

    /*package*/ final Flags flags;

    public Forecast(
            double latitude,
            double longitude,
            String timezone,
            int offset,
            DataPoint currently,
            DataBlock minutely,
            DataBlock hourly,
            DataBlock daily,
            ArrayList<Alert> alerts,
            Flags flags) {
        this.latitude = latitude;
        this.longitude = longitude;
        this.timezone = timezone;
        this.offset = offset;
        this.currently = currently;
        this.minutely = minutely;
        this.hourly = hourly;
        this.daily = daily;
        this.alerts = alerts;
        this.flags = flags;
    }

    public double getLatitude() {
        return latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public String getTimezone() {
        return timezone;
    }

    public int getOffset() {
        return offset;
    }

    public DataPoint getCurrently() {
        return currently;
    }

    public DataBlock getMinutely() {
        return minutely;
    }

    public DataBlock getHourly() {
        return hourly;
    }

    public DataBlock getDaily() {
        return daily;
    }

    public ArrayList<Alert> getAlerts() {
        return alerts;
    }

    public Flags getFlags() {
        return flags;
    }
}
