// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

package com.wta.weather;

public abstract class NetworkController {
    public abstract byte[] get(String URI);

    public abstract byte[] post(String URI, byte[] body);
}
