// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

package com.wta.weather;

public abstract class NetworkController {
    public abstract void get(String URI, WeatherController controller);

    public abstract byte[] post(String URI, byte[] body);

    public abstract void callbackNative(Forecast result);
}
