// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

package com.wta.weather;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class WeatherController {
    public abstract Forecast forecast(double latitude, double longitude);

    public static native WeatherController createWithNetworkController(NetworkController controller);

    public static final class CppProxy extends WeatherController
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public Forecast forecast(double latitude, double longitude)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_forecast(this.nativeRef, latitude, longitude);
        }
        private native Forecast native_forecast(long _nativeRef, double latitude, double longitude);
    }
}
