// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import <Foundation/Foundation.h>

@interface MTAlert : NSObject
- (nonnull id)initWithTitle:(nonnull NSString *)title
                    expires:(int64_t)expires
           alertDescription:(nonnull NSString *)alertDescription
                        uri:(nonnull NSString *)uri;

@property (nonatomic, readonly, nonnull) NSString * title;

@property (nonatomic, readonly) int64_t expires;

@property (nonatomic, readonly, nonnull) NSString * alertDescription;

@property (nonatomic, readonly, nonnull) NSString * uri;

@end
