// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTAlert.h"


@implementation MTAlert

- (id)initWithTitle:(nonnull NSString *)title
            expires:(int64_t)expires
   alertDescription:(nonnull NSString *)alertDescription
                uri:(nonnull NSString *)uri
{
    if (self = [super init]) {
        _title = [title copy];
        _expires = expires;
        _alertDescription = [alertDescription copy];
        _uri = [uri copy];
    }
    return self;
}

@end
