// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTDataPoint.h"
#import <Foundation/Foundation.h>

@interface MTDataBlock : NSObject
- (nonnull id)initWithSummary:(nonnull NSString *)summary
                         icon:(nonnull NSString *)icon
                         data:(nonnull NSArray *)data;

@property (nonatomic, readonly, nonnull) NSString * summary;

@property (nonatomic, readonly, nonnull) NSString * icon;

@property (nonatomic, readonly, nonnull) NSArray * data;

@end
