// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTDataBlock.h"


@implementation MTDataBlock

- (id)initWithSummary:(nonnull NSString *)summary
                 icon:(nonnull NSString *)icon
                 data:(nonnull NSArray *)data
{
    if (self = [super init]) {
        _summary = [summary copy];
        _icon = [icon copy];
        _data = data;
    }
    return self;
}

@end
