// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import <Foundation/Foundation.h>

@interface MTDataPoint : NSObject
- (nonnull id)initWithTime:(int64_t)time
                   summary:(nonnull NSString *)summary
                      icon:(nonnull NSString *)icon
               sunriseTime:(nullable NSNumber *)sunriseTime
                sunsetTime:(nullable NSNumber *)sunsetTime
                 moonPhase:(nullable NSNumber *)moonPhase
      nearestStormDistance:(nullable NSNumber *)nearestStormDistance
       nearestStormBearing:(nullable NSNumber *)nearestStormBearing
           precipIntensity:(double)precipIntensity
        precipIntensityMax:(nullable NSNumber *)precipIntensityMax
    precipIntensityMaxTime:(nullable NSNumber *)precipIntensityMaxTime
         precipProbability:(double)precipProbability
                precipType:(nonnull NSString *)precipType
        precipAccumulation:(nullable NSNumber *)precipAccumulation
               temperature:(nullable NSNumber *)temperature
            temperatureMin:(nullable NSNumber *)temperatureMin
        temperatureMinTime:(nullable NSNumber *)temperatureMinTime
            temperatureMax:(nullable NSNumber *)temperatureMax
        temperatureMaxTime:(nullable NSNumber *)temperatureMaxTime
       apparentTemperature:(nullable NSNumber *)apparentTemperature
    apparentTemperatureMax:(nullable NSNumber *)apparentTemperatureMax
apparentTemperatureMaxTime:(nullable NSNumber *)apparentTemperatureMaxTime
    apparentTemperatureMin:(nullable NSNumber *)apparentTemperatureMin
apparentTemperatureMinTime:(nullable NSNumber *)apparentTemperatureMinTime
                  dewPoint:(double)dewPoint
                 windSpeed:(double)windSpeed
               windBearing:(double)windBearing
                cloudCover:(double)cloudCover
                  humidity:(double)humidity
                  pressure:(double)pressure
                visibility:(double)visibility
                     ozone:(double)ozone;

@property (nonatomic, readonly) int64_t time;

@property (nonatomic, readonly, nonnull) NSString * summary;

@property (nonatomic, readonly, nonnull) NSString * icon;

@property (nonatomic, readonly, nullable) NSNumber * sunriseTime;

@property (nonatomic, readonly, nullable) NSNumber * sunsetTime;

@property (nonatomic, readonly, nullable) NSNumber * moonPhase;

@property (nonatomic, readonly, nullable) NSNumber * nearestStormDistance;

@property (nonatomic, readonly, nullable) NSNumber * nearestStormBearing;

@property (nonatomic, readonly) double precipIntensity;

@property (nonatomic, readonly, nullable) NSNumber * precipIntensityMax;

@property (nonatomic, readonly, nullable) NSNumber * precipIntensityMaxTime;

@property (nonatomic, readonly) double precipProbability;

@property (nonatomic, readonly, nonnull) NSString * precipType;

@property (nonatomic, readonly, nullable) NSNumber * precipAccumulation;

@property (nonatomic, readonly, nullable) NSNumber * temperature;

@property (nonatomic, readonly, nullable) NSNumber * temperatureMin;

@property (nonatomic, readonly, nullable) NSNumber * temperatureMinTime;

@property (nonatomic, readonly, nullable) NSNumber * temperatureMax;

@property (nonatomic, readonly, nullable) NSNumber * temperatureMaxTime;

@property (nonatomic, readonly, nullable) NSNumber * apparentTemperature;

@property (nonatomic, readonly, nullable) NSNumber * apparentTemperatureMax;

@property (nonatomic, readonly, nullable) NSNumber * apparentTemperatureMaxTime;

@property (nonatomic, readonly, nullable) NSNumber * apparentTemperatureMin;

@property (nonatomic, readonly, nullable) NSNumber * apparentTemperatureMinTime;

@property (nonatomic, readonly) double dewPoint;

@property (nonatomic, readonly) double windSpeed;

@property (nonatomic, readonly) double windBearing;

@property (nonatomic, readonly) double cloudCover;

@property (nonatomic, readonly) double humidity;

@property (nonatomic, readonly) double pressure;

@property (nonatomic, readonly) double visibility;

@property (nonatomic, readonly) double ozone;

@end
