// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTDataPoint.h"


@implementation MTDataPoint

- (id)initWithTime:(int64_t)time
           summary:(nonnull NSString *)summary
              icon:(nonnull NSString *)icon
       sunriseTime:(nullable NSNumber *)sunriseTime
        sunsetTime:(nullable NSNumber *)sunsetTime
         moonPhase:(nullable NSNumber *)moonPhase
nearestStormDistance:(nullable NSNumber *)nearestStormDistance
nearestStormBearing:(nullable NSNumber *)nearestStormBearing
   precipIntensity:(double)precipIntensity
precipIntensityMax:(nullable NSNumber *)precipIntensityMax
precipIntensityMaxTime:(nullable NSNumber *)precipIntensityMaxTime
 precipProbability:(double)precipProbability
        precipType:(nonnull NSString *)precipType
precipAccumulation:(nullable NSNumber *)precipAccumulation
       temperature:(nullable NSNumber *)temperature
    temperatureMin:(nullable NSNumber *)temperatureMin
temperatureMinTime:(nullable NSNumber *)temperatureMinTime
    temperatureMax:(nullable NSNumber *)temperatureMax
temperatureMaxTime:(nullable NSNumber *)temperatureMaxTime
apparentTemperature:(nullable NSNumber *)apparentTemperature
apparentTemperatureMax:(nullable NSNumber *)apparentTemperatureMax
apparentTemperatureMaxTime:(nullable NSNumber *)apparentTemperatureMaxTime
apparentTemperatureMin:(nullable NSNumber *)apparentTemperatureMin
apparentTemperatureMinTime:(nullable NSNumber *)apparentTemperatureMinTime
          dewPoint:(double)dewPoint
         windSpeed:(double)windSpeed
       windBearing:(double)windBearing
        cloudCover:(double)cloudCover
          humidity:(double)humidity
          pressure:(double)pressure
        visibility:(double)visibility
             ozone:(double)ozone
{
    if (self = [super init]) {
        _time = time;
        _summary = [summary copy];
        _icon = [icon copy];
        _sunriseTime = sunriseTime;
        _sunsetTime = sunsetTime;
        _moonPhase = moonPhase;
        _nearestStormDistance = nearestStormDistance;
        _nearestStormBearing = nearestStormBearing;
        _precipIntensity = precipIntensity;
        _precipIntensityMax = precipIntensityMax;
        _precipIntensityMaxTime = precipIntensityMaxTime;
        _precipProbability = precipProbability;
        _precipType = [precipType copy];
        _precipAccumulation = precipAccumulation;
        _temperature = temperature;
        _temperatureMin = temperatureMin;
        _temperatureMinTime = temperatureMinTime;
        _temperatureMax = temperatureMax;
        _temperatureMaxTime = temperatureMaxTime;
        _apparentTemperature = apparentTemperature;
        _apparentTemperatureMax = apparentTemperatureMax;
        _apparentTemperatureMaxTime = apparentTemperatureMaxTime;
        _apparentTemperatureMin = apparentTemperatureMin;
        _apparentTemperatureMinTime = apparentTemperatureMinTime;
        _dewPoint = dewPoint;
        _windSpeed = windSpeed;
        _windBearing = windBearing;
        _cloudCover = cloudCover;
        _humidity = humidity;
        _pressure = pressure;
        _visibility = visibility;
        _ozone = ozone;
    }
    return self;
}

@end
