// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import <Foundation/Foundation.h>

@interface MTFlags : NSObject
- (nonnull id)initWithDarkskyUnavailable:(nullable NSString *)darkskyUnavailable
                         darkskyStations:(nullable NSArray *)darkskyStations
                       datapointStations:(nullable NSArray *)datapointStations
                             isdStations:(nullable NSArray *)isdStations
                            lampStations:(nullable NSArray *)lampStations
                           metarStations:(nullable NSArray *)metarStations
                            metnoLicense:(nullable NSString *)metnoLicense
                                 sources:(nullable NSArray *)sources
                                   units:(nullable NSString *)units;

@property (nonatomic, readonly, nullable) NSString * darkskyUnavailable;

@property (nonatomic, readonly, nullable) NSArray * darkskyStations;

@property (nonatomic, readonly, nullable) NSArray * datapointStations;

@property (nonatomic, readonly, nullable) NSArray * isdStations;

@property (nonatomic, readonly, nullable) NSArray * lampStations;

@property (nonatomic, readonly, nullable) NSArray * metarStations;

@property (nonatomic, readonly, nullable) NSString * metnoLicense;

@property (nonatomic, readonly, nullable) NSArray * sources;

@property (nonatomic, readonly, nullable) NSString * units;

@end
