// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTFlags.h"


@implementation MTFlags

- (id)initWithDarkskyUnavailable:(nullable NSString *)darkskyUnavailable
                 darkskyStations:(nullable NSArray *)darkskyStations
               datapointStations:(nullable NSArray *)datapointStations
                     isdStations:(nullable NSArray *)isdStations
                    lampStations:(nullable NSArray *)lampStations
                   metarStations:(nullable NSArray *)metarStations
                    metnoLicense:(nullable NSString *)metnoLicense
                         sources:(nullable NSArray *)sources
                           units:(nullable NSString *)units
{
    if (self = [super init]) {
        _darkskyUnavailable = [darkskyUnavailable copy];
        _darkskyStations = darkskyStations;
        _datapointStations = datapointStations;
        _isdStations = isdStations;
        _lampStations = lampStations;
        _metarStations = metarStations;
        _metnoLicense = [metnoLicense copy];
        _sources = sources;
        _units = [units copy];
    }
    return self;
}

@end
