// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTAlert.h"
#import "MTDataBlock.h"
#import "MTDataPoint.h"
#import "MTFlags.h"
#import <Foundation/Foundation.h>

@interface MTForecast : NSObject
- (nonnull id)initWithLatitude:(double)latitude
                     longitude:(double)longitude
                      timezone:(nonnull NSString *)timezone
                        offset:(int32_t)offset
                     currently:(nonnull MTDataPoint *)currently
                      minutely:(nonnull MTDataBlock *)minutely
                        hourly:(nonnull MTDataBlock *)hourly
                         daily:(nonnull MTDataBlock *)daily
                        alerts:(nonnull NSArray *)alerts
                         flags:(nonnull MTFlags *)flags;

@property (nonatomic, readonly) double latitude;

@property (nonatomic, readonly) double longitude;

@property (nonatomic, readonly, nonnull) NSString * timezone;

@property (nonatomic, readonly) int32_t offset;

@property (nonatomic, readonly, nonnull) MTDataPoint * currently;

@property (nonatomic, readonly, nonnull) MTDataBlock * minutely;

@property (nonatomic, readonly, nonnull) MTDataBlock * hourly;

@property (nonatomic, readonly, nonnull) MTDataBlock * daily;

@property (nonatomic, readonly, nonnull) NSArray * alerts;

@property (nonatomic, readonly, nonnull) MTFlags * flags;

@end
