// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTForecast.h"


@implementation MTForecast

- (id)initWithLatitude:(double)latitude
             longitude:(double)longitude
              timezone:(nonnull NSString *)timezone
                offset:(int32_t)offset
             currently:(nonnull MTDataPoint *)currently
              minutely:(nonnull MTDataBlock *)minutely
                hourly:(nonnull MTDataBlock *)hourly
                 daily:(nonnull MTDataBlock *)daily
                alerts:(nonnull NSArray *)alerts
                 flags:(nonnull MTFlags *)flags
{
    if (self = [super init]) {
        _latitude = latitude;
        _longitude = longitude;
        _timezone = [timezone copy];
        _offset = offset;
        _currently = currently;
        _minutely = minutely;
        _hourly = hourly;
        _daily = daily;
        _alerts = alerts;
        _flags = flags;
    }
    return self;
}

@end
