// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import <Foundation/Foundation.h>


@protocol MTNetworkController

- (nonnull NSData *)get:(nonnull NSString *)URI;

- (nonnull NSData *)post:(nonnull NSString *)URI
                    body:(nonnull NSData *)body;

@end
