// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTForecast.h"
#import <Foundation/Foundation.h>
@class MTWeatherController;


@protocol MTNetworkController

- (void)get:(nonnull NSString *)URI
 controller:(nullable MTWeatherController *)controller;

- (nonnull NSData *)post:(nonnull NSString *)URI
                    body:(nonnull NSData *)body;

- (void)callbackNative:(nonnull MTForecast *)result;

@end
