// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import <Foundation/Foundation.h>
@class MTWeatherController;
@protocol MTNetworkController;


@interface MTWeatherController : NSObject

- (void)forecast:(double)latitude
       longitude:(double)longitude;

+ (nullable MTWeatherController *)createWithNetworkController:(nullable id<MTNetworkController>)controller;

- (void)receiveData:(nonnull NSData *)data;

@end
