// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTForecast.h"
#import <Foundation/Foundation.h>
@class MTWeatherController;
@protocol MTNetworkController;


@interface MTWeatherController : NSObject

- (nonnull MTForecast *)forecast:(double)latitude
                       longitude:(double)longitude;

+ (nullable MTWeatherController *)createWithNetworkController:(nullable id<MTNetworkController>)controller;

@end
