// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTAlert.h"
#include "alert.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MTAlert;

namespace djinni_generated {

struct Alert
{
    using CppType = ::Alert;
    using ObjcType = MTAlert*;

    using Boxed = Alert;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
