// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTAlert+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Alert::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.title),
            ::djinni::I64::toCpp(obj.expires),
            ::djinni::String::toCpp(obj.alertDescription),
            ::djinni::String::toCpp(obj.uri)};
}

auto Alert::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[MTAlert alloc] initWithTitle:(::djinni::String::fromCpp(cpp.title))
                                  expires:(::djinni::I64::fromCpp(cpp.expires))
                         alertDescription:(::djinni::String::fromCpp(cpp.alert_description))
                                      uri:(::djinni::String::fromCpp(cpp.uri))];
}

}  // namespace djinni_generated
