// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTDataPoint.h"
#include "dataPoint.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MTDataPoint;

namespace djinni_generated {

struct DataPoint
{
    using CppType = ::DataPoint;
    using ObjcType = MTDataPoint*;

    using Boxed = DataPoint;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
