// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTDataBlock.h"
#include "dataBlock.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MTDataBlock;

namespace djinni_generated {

struct DataBlock
{
    using CppType = ::DataBlock;
    using ObjcType = MTDataBlock*;

    using Boxed = DataBlock;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
