// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTForecast+Private.h"
#import "DJIMarshal+Private.h"
#import "MTAlert+Private.h"
#import "MTDataBlock+Private.h"
#import "MTDataPoint+Private.h"
#import "MTFlags+Private.h"
#include <cassert>

namespace djinni_generated {

auto Forecast::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::F64::toCpp(obj.latitude),
            ::djinni::F64::toCpp(obj.longitude),
            ::djinni::String::toCpp(obj.timezone),
            ::djinni::I32::toCpp(obj.offset),
            ::djinni_generated::DataPoint::toCpp(obj.currently),
            ::djinni_generated::DataBlock::toCpp(obj.minutely),
            ::djinni_generated::DataBlock::toCpp(obj.hourly),
            ::djinni_generated::DataBlock::toCpp(obj.daily),
            ::djinni::List<::djinni_generated::Alert>::toCpp(obj.alerts),
            ::djinni_generated::Flags::toCpp(obj.flags)};
}

auto Forecast::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[MTForecast alloc] initWithLatitude:(::djinni::F64::fromCpp(cpp.latitude))
                                      longitude:(::djinni::F64::fromCpp(cpp.longitude))
                                       timezone:(::djinni::String::fromCpp(cpp.timezone))
                                         offset:(::djinni::I32::fromCpp(cpp.offset))
                                      currently:(::djinni_generated::DataPoint::fromCpp(cpp.currently))
                                       minutely:(::djinni_generated::DataBlock::fromCpp(cpp.minutely))
                                         hourly:(::djinni_generated::DataBlock::fromCpp(cpp.hourly))
                                          daily:(::djinni_generated::DataBlock::fromCpp(cpp.daily))
                                         alerts:(::djinni::List<::djinni_generated::Alert>::fromCpp(cpp.alerts))
                                          flags:(::djinni_generated::Flags::fromCpp(cpp.flags))];
}

}  // namespace djinni_generated
