// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#import "MTForecast.h"
#include "forecast.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MTForecast;

namespace djinni_generated {

struct Forecast
{
    using CppType = ::Forecast;
    using ObjcType = MTForecast*;

    using Boxed = Forecast;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
