// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#include "network_controller.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol MTNetworkController;

namespace djinni_generated {

class NetworkController
{
public:
    using CppType = std::shared_ptr<::NetworkController>;
    using ObjcType = id<MTNetworkController>;

    using Boxed = NetworkController;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

