// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from weather.idl

#include "weatherController.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MTWeatherController;

namespace djinni_generated {

class WeatherController
{
public:
    using CppType = std::shared_ptr<::WeatherController>;
    using ObjcType = MTWeatherController*;

    using Boxed = WeatherController;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

